### ISSUE TITLE
Application scaling too large after switch to new launcher

### ISSUE THREAD

**Issue by Grehgous** [open-osrs/runelite#1733]
After switching to the new launcher 2.1.6.0 the game is much larger than it was previously. I have tried all of the high DPI settings override options, but to no avail. I have also tried deleting the .runelite folder and trying with and without custom chrome. The client and launcher logs both look fine.

Comparison of OPRS after the client update and RuneLite, which had the same behavior as RL+ with the old launcher.

![image](https://user-images.githubusercontent.com/23343347/66281144-034bb400-e888-11e9-9e61-74e037d246d7.png)

**Comment by whocodes** [comment]
Can we see the entire content of this portion of Windows settings?

![](https://whocodes.tech/upload/uDLlXZqhUp.png)

**Comment by Grehgous** [comment]
> Can we see the entire content of this portion of Windows settings?
> 
> ![](https://camo.githubusercontent.com/838804d712b17e91950e19c791f25723816be87a/68747470733a2f2f77686f636f6465732e746563682f75706c6f61642f75444c6c585a716855702e706e67)

![image](https://user-images.githubusercontent.com/23343347/66286433-7d3b6780-e89f-11e9-9724-fbf3e33088f1.png)

**Comment by deathguard6** [comment]
A quick and dirty fix is to turn off system wide scaling. This issue should be solved via the same process as runelite https://github.com/runelite/runelite/wiki/Change-DPI-Scaling-(Windows) it however does not seem to be working now.

This fix will disable all scaling for your machine and return to your systems display resolution everything will look smaller. but openrs will be the correct size.
To turn off system scaling 
1. In the search box on the taskbar, type advanced scaling settings and select Fix apps that are blurry.
2. set custom scaling to 100% and turn off let windows try fix blurry apps
![image](https://user-images.githubusercontent.com/47849843/66286489-3b0d3700-e92e-11e9-9377-93a1451378e3.png)
3. click apply
4. log off and log in again

**Comment by whocodes** [comment]
Try changing the `High DPI scaling override` setting for `javaw.exe` in your Java installation, instead of just for the client launcher.

**Comment by Grehgous** [comment]
> Try changing the DPI setting for `javaw.exe` in your Java installation, instead of just for the client launcher.

I tried changing that for `javaw.exe` and `java.exe`, but there was no change.

**Comment by brimmy11** [comment]
If you are using the .jar version of OOSRS you can fix this by simply setting a dpi scaling override on your java and javaw executables to have the system perform the scaling.

**Comment by Genesee101** [comment]
I'm having the same exact problem. I also changed the dpi settings for java and javaw and that has not worked either.

**Comment by zeruth** [comment]
Scaling is now correct, not the other way around. Scaling was broken on JRE8. We now use JRE11

**Comment by Grehgous** [comment]
> If you are using the .jar version of OOSRS you can fix this by simply setting a dpi scaling override on your java and javaw executables to have the system perform the scaling.

I tried that with the .jar and the scaling is no different than with the .exe

**Comment by GrimWrath** [comment]
I had a similar issue. I am using a 14" screen with a 1920 x 1080 resolution. Before the W10 creator's update, W10 had pretty awful DPI scaling, so a 3rd party program was floating around that could force it to use windows 8.1 scaling. It is possible you might have used this program a long time ago and forgot about it.  It is located here http://windows10-dpi-fix.xpexplorer.com/
You can use it to revert the dpi changes. After that, you can reset your dpi scaling to 100% through the windows display settings, and then upscale with default windows 10 options, and the problem should be fixed.

**Comment by Grehgous** [comment]
@GrimWrath I remember using that app years ago. Just downloaded it, set it to win10 default, restarted twice, and am still having the same issues.

**Comment by Grehgous** [comment]
![image](https://user-images.githubusercontent.com/23343347/70879347-f687c280-1f92-11ea-9535-3ce26fffe48a.png)

**Comment by Owain94** [comment]
Issue is invalid
